language: python
python:
- "3.7.10"
# setup environment
env:
- DJANGO_VERSION=1.11.2
- DJANGO_SETTINGS_MODULE='weatherapi.settings'
# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- pytest
