language: python
python:
- "2.7"
# setup environment
env:
- DJANGO_VERSION=3.1.3
- DJANGO_SETTINGS_MODULE='weatherapi.settings'
# install dependencies
install:
- pip install pipenv
- pipenv install

# run test scripts
script:
- pytest
