language: python
python:
- "2.7"
- "3.5"
- "3.7"
# setup environment
env:
- DJANGO_VERSION=3.1.3
- DJANGO_SETTINGS_MODULE='weatherapi.settings'
# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- pytest
