language: python
python:
- "3.7"
# setup environment
env:
- DJANGO_VERSION=3.1.3
- DJANGO_SETTINGS_MODULE='weatherapi.settings'
# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- pytest

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t coverage.py
  - nyc report --reporter=html
  
# save coverage
after_success:
  - "coveralls"
